default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV["DEV_DB_URL"] %>

test:
  <<: *default
  database: <%= ENV["DEV_DB_URL"] %>

production:
  <<: *default
  database: <%= ENV["PROD_DB_URL"] %>
